version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: ChangeMeSuperSecure2025!
      POSTGRES_DB: rails_production
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
    env_file:
      - .env.production
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://rails:ChangeMeSuperSecure2025!@db:5432/rails_production
    ports:
      - "3000:80"
    depends_on:
      - db
    volumes:
      - .:/rails
